package com.example.mediaapp.viewModels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.mediaapp.R
import com.example.mediaapp.backend.auth.AuthRepository
import com.example.mediaapp.models.CurrentUser
import com.example.mediaapp.backend.database.DatabaseRepository
import com.example.mediaapp.models.Country
import com.example.mediaapp.models.User
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class CurrentUserViewModel(
    private val authRepository: AuthRepository,
    private val databaseRepository: DatabaseRepository
) : ViewModel(){

    private val _currentUser = MutableStateFlow<CurrentUser?>(null)
    val currentUser: StateFlow<CurrentUser?> = _currentUser.asStateFlow()

    var username = ""
    var name = ""
    var desc = ""
    var location = ""

    fun getCurrentUser() {
        viewModelScope.launch {
            _currentUser.value = databaseRepository.getUserProfile()
        }
    }

    fun getCountryFlag(countryName: String): Int {
        val country = countries.find { it.name == countryName }
        return country?.flag ?: -1
    }

    fun getCountryNames(): List<String> {
        return countries.map { it.name }
    }

    fun updateAccountDetails() {
        val Tempuser = User(
            if (username == "") _currentUser.value!!.user.username else username,
            if (name == ("")) _currentUser.value!!.user.name else name,
            if (location == ("")) _currentUser.value!!.user.location else location,
            _currentUser.value!!.user.followers,
            _currentUser.value!!.user.following,
            if (desc == ("")) _currentUser.value!!.user.description else desc,
            _currentUser.value!!.user.profilePicture,
            _currentUser.value!!.user.stats,
            _currentUser.value!!.user.favorites,
            _currentUser.value!!.user.recentlyWatched,
            _currentUser.value!!.user.ratedMovies
        )
        viewModelScope.launch {
            val user = authRepository.getCurrentUser()

            databaseRepository.updateUserProfile(
                user!!.uid,
                User.toMap(Tempuser)
            )
        }
        getCurrentUser()
    }

    private val countries = listOf(
        Country("Andorra", R.drawable.ad),
        Country("United Arab Emirates", R.drawable.ae),
        Country("Afghanistan", R.drawable.af),
        Country("Antigua and Barbuda", R.drawable.ag),
        Country("Anguilla", R.drawable.ai),
        Country("Albania", R.drawable.al),
        Country("Armenia", R.drawable.am),
        Country("Angola", R.drawable.ao),
        Country("Antarctica", R.drawable.aq),
        Country("Argentina", R.drawable.ar),
        Country("American Samoa", R.drawable.as_),
        Country("Austria", R.drawable.at),
        Country("Australia", R.drawable.au),
        Country("Aruba", R.drawable.aw),
        Country("Åland Islands", R.drawable.ax),
        Country("Azerbaijan", R.drawable.az),
        Country("Bosnia and Herzegovina", R.drawable.ba),
        Country("Barbados", R.drawable.bb),
        Country("Bangladesh", R.drawable.bd),
        Country("Belgium", R.drawable.be),
        Country("Burkina Faso", R.drawable.bf),
        Country("Bulgaria", R.drawable.bg),
        Country("Bahrain", R.drawable.bh),
        Country("Burundi", R.drawable.bi),
        Country("Benin", R.drawable.bj),
        Country("Saint Barthélemy", R.drawable.bl),
        Country("Bermuda", R.drawable.bm),
        Country("Brunei Darussalam", R.drawable.bn),
        Country("Bolivia (Plurinational State of)", R.drawable.bo),
        Country("Bonaire, Sint Eustatius and Saba", R.drawable.bq),
        Country("Brazil", R.drawable.br),
        Country("Bahamas", R.drawable.bs),
        Country("Bhutan", R.drawable.bt),
        Country("Bouvet Island", R.drawable.bv),
        Country("Botswana", R.drawable.bw),
        Country("Belarus", R.drawable.by),
        Country("Belize", R.drawable.bz),
        Country("Canada", R.drawable.ca),
        Country("Cocos (Keeling) Islands", R.drawable.cc),
        Country("Congo, Democratic Republic of the", R.drawable.cd),
        Country("Central African Republic", R.drawable.cf),
        Country("Congo", R.drawable.cg),
        Country("Switzerland", R.drawable.ch),
        Country("Côte d'Ivoire", R.drawable.ci),
        Country("Cook Islands", R.drawable.ck),
        Country("Chile", R.drawable.cl),
        Country("Cameroon", R.drawable.cm),
        Country("China", R.drawable.cn),
        Country("Colombia", R.drawable.co),
        Country("Costa Rica", R.drawable.cr),
        Country("Cuba", R.drawable.cu),
        Country("Cabo Verde", R.drawable.cv),
        Country("Curaçao", R.drawable.cw),
        Country("Christmas Island", R.drawable.cx),
        Country("Cyprus", R.drawable.cy),
        Country("Czechia", R.drawable.cz),
        Country("Germany", R.drawable.de),
        Country("Djibouti", R.drawable.dj),
        Country("Denmark", R.drawable.dk),
        Country("Dominica", R.drawable.dm),
        Country("Dominican Republic", R.drawable.do_),
        Country("Algeria", R.drawable.dz),
        Country("Ecuador", R.drawable.ec),
        Country("Estonia", R.drawable.ee),
        Country("Egypt", R.drawable.eg),
        Country("Western Sahara", R.drawable.eh),
        Country("Eritrea", R.drawable.er),
        Country("Spain", R.drawable.es),
        Country("Ethiopia", R.drawable.et),
        Country("Finland", R.drawable.fi),
        Country("Fiji", R.drawable.fj),
        Country("Falkland Islands (Malvinas)", R.drawable.fk),
        Country("Micronesia (Federated States of)", R.drawable.fm),
        Country("Faroe Islands", R.drawable.fo),
        Country("France", R.drawable.fr),
        Country("Gabon", R.drawable.ga),
        Country("The United Kingdom", R.drawable.gb),
        Country("Grenada", R.drawable.gd),
        Country("Georgia", R.drawable.ge),
        Country("French Guiana", R.drawable.gf),
        Country("Guernsey", R.drawable.gg),
        Country("Ghana", R.drawable.gh),
        Country("Gibraltar", R.drawable.gi),
        Country("Greenland", R.drawable.gl),
        Country("Gambia", R.drawable.gm),
        Country("Guinea", R.drawable.gn),
        Country("Guadeloupe", R.drawable.gp),
        Country("Equatorial Guinea", R.drawable.gq),
        Country("Greece", R.drawable.gr),
        Country("South Georgia and the South Sandwich Islands", R.drawable.gs),
        Country("Guatemala", R.drawable.gt),
        Country("Guam", R.drawable.gu),
        Country("Guinea-Bissau", R.drawable.gw),
        Country("Guyana", R.drawable.gy),
        Country("Hong Kong", R.drawable.hk),
        Country("Heard Island and McDonald Islands", R.drawable.hm),
        Country("Honduras", R.drawable.hn),
        Country("Croatia", R.drawable.hr),
        Country("Haiti", R.drawable.ht),
        Country("Hungary", R.drawable.hu),
        Country("Indonesia", R.drawable.id),
        Country("Ireland", R.drawable.ie),
        Country("Israel", R.drawable.il),
        Country("Isle of Man", R.drawable.im),
        Country("India", R.drawable.in_),
        Country("British Indian Ocean Territory", R.drawable.io),
        Country("Iraq", R.drawable.iq),
        Country("Iran (Islamic Republic of)", R.drawable.ir),
        Country("Iceland", R.drawable.is_),
        Country("Italy", R.drawable.it),
        Country("Jersey", R.drawable.je),
        Country("Jamaica", R.drawable.jm),
        Country("Jordan", R.drawable.jo),
        Country("Japan", R.drawable.jp),
        Country("Kenya", R.drawable.ke),
        Country("Kyrgyzstan", R.drawable.kg),
        Country("Cambodia", R.drawable.kh),
        Country("Kiribati", R.drawable.ki),
        Country("Comoros", R.drawable.km),
        Country("Saint Kitts and Nevis", R.drawable.kn),
        Country("Korea (Democratic People's Republic of)", R.drawable.kp),
        Country("Korea, Republic of", R.drawable.kr),
        Country("Kuwait", R.drawable.kw),
        Country("Cayman Islands", R.drawable.ky),
        Country("Kazakhstan", R.drawable.kz),
        Country("Lao People's Democratic Republic", R.drawable.la),
        Country("Lebanon", R.drawable.lb),
        Country("Saint Lucia", R.drawable.lc),
        Country("Liechtenstein", R.drawable.li),
        Country("Sri Lanka", R.drawable.lk),
        Country("Liberia", R.drawable.lr),
        Country("Lesotho", R.drawable.ls),
        Country("Lithuania", R.drawable.lt),
        Country("Luxembourg", R.drawable.lu),
        Country("Latvia", R.drawable.lv),
        Country("Libya", R.drawable.ly),
        Country("Morocco", R.drawable.ma),
        Country("Monaco", R.drawable.mc),
        Country("Moldova, Republic of", R.drawable.md),
        Country("Montenegro", R.drawable.me),
        Country("Saint Martin (French part)", R.drawable.mf),
        Country("Madagascar", R.drawable.mg),
        Country("Marshall Islands", R.drawable.mh),
        Country("North Macedonia", R.drawable.mk),
        Country("Mali", R.drawable.ml),
        Country("Myanmar", R.drawable.mm),
        Country("Mongolia", R.drawable.mn),
        Country("Macao", R.drawable.mo),
        Country("Northern Mariana Islands", R.drawable.mp),
        Country("Martinique", R.drawable.mq),
        Country("Mauritania", R.drawable.mr),
        Country("Montserrat", R.drawable.ms),
        Country("Malta", R.drawable.mt),
        Country("Mauritius", R.drawable.mu),
        Country("Maldives", R.drawable.mv),
        Country("Malawi", R.drawable.mw),
        Country("Mexico", R.drawable.mx),
        Country("Malaysia", R.drawable.my),
        Country("Mozambique", R.drawable.mz),
        Country("Namibia", R.drawable.na),
        Country("New Caledonia", R.drawable.nc),
        Country("Niger", R.drawable.ne),
        Country("Norfolk Island", R.drawable.nf),
        Country("Nigeria", R.drawable.ng),
        Country("Nicaragua", R.drawable.ni),
        Country("Netherlands", R.drawable.nl),
        Country("Norway", R.drawable.no),
        Country("Nepal", R.drawable.np),
        Country("Nauru", R.drawable.nr),
        Country("Niue", R.drawable.nu),
        Country("New Zealand", R.drawable.nz),
        Country("Oman", R.drawable.om),
        Country("Panama", R.drawable.pa),
        Country("Peru", R.drawable.pe),
        Country("French Polynesia", R.drawable.pf),
        Country("Papua New Guinea", R.drawable.pg),
        Country("Philippines", R.drawable.ph),
        Country("Pakistan", R.drawable.pk),
        Country("Poland", R.drawable.pl),
        Country("Saint Pierre and Miquelon", R.drawable.pm),
        Country("Pitcairn", R.drawable.pn),
        Country("Puerto Rico", R.drawable.pr),
        Country("Palestine, State of", R.drawable.ps),
        Country("Portugal", R.drawable.pt),
        Country("Palau", R.drawable.pw),
        Country("Paraguay", R.drawable.py),
        Country("Qatar", R.drawable.qa),
        Country("Réunion", R.drawable.re),
        Country("Romania", R.drawable.ro),
        Country("Serbia", R.drawable.rs),
        Country("Russian Federation", R.drawable.ru),
        Country("Rwanda", R.drawable.rw),
        Country("Saudi Arabia", R.drawable.sa),
        Country("Solomon Islands", R.drawable.sb),
        Country("Seychelles", R.drawable.sc),
        Country("Sudan", R.drawable.sd),
        Country("Sweden", R.drawable.se),
        Country("Singapore", R.drawable.sg),
        Country("Saint Helena, Ascension and Tristan da Cunha", R.drawable.sh),
        Country("Slovenia", R.drawable.si),
        Country("Svalbard and Jan Mayen", R.drawable.sj),
        Country("Slovakia", R.drawable.sk),
        Country("Sierra Leone", R.drawable.sl),
        Country("San Marino", R.drawable.sm),
        Country("Senegal", R.drawable.sn),
        Country("Somalia", R.drawable.so),
        Country("Suriname", R.drawable.sr),
        Country("South Sudan", R.drawable.ss),
        Country("Sao Tome and Principe", R.drawable.st),
        Country("El Salvador", R.drawable.sv),
        Country("Sint Maarten (Dutch part)", R.drawable.sx),
        Country("Syrian Arab Republic", R.drawable.sy),
        Country("Eswatini", R.drawable.sz),
        Country("Turks and Caicos Islands", R.drawable.tc),
        Country("Chad", R.drawable.td),
        Country("French Southern Territories", R.drawable.tf),
        Country("Togo", R.drawable.tg),
        Country("Thailand", R.drawable.th),
        Country("Tajikistan", R.drawable.tj),
        Country("Tokelau", R.drawable.tk),
        Country("Timor-Leste", R.drawable.tl),
        Country("Turkmenistan", R.drawable.tm),
        Country("Tunisia", R.drawable.tn),
        Country("Tonga", R.drawable.to),
        Country("Turkey", R.drawable.tr),
        Country("Trinidad and Tobago", R.drawable.tt),
        Country("Tuvalu", R.drawable.tv),
        Country("Taiwan, Province of China", R.drawable.tw),
        Country("Tanzania, United Republic of", R.drawable.tz),
        Country("Ukraine", R.drawable.ua),
        Country("Uganda", R.drawable.ug),
        Country("United States Minor Outlying Islands", R.drawable.um),
        Country("United States of America", R.drawable.us),
        Country("Uruguay", R.drawable.uy),
        Country("Uzbekistan", R.drawable.uz),
        Country("Holy See", R.drawable.va),
        Country("Saint Vincent and the Grenadines", R.drawable.vc),
        Country("Venezuela (Bolivarian Republic of)", R.drawable.ve),
        Country("Virgin Islands (British)", R.drawable.vg),
        Country("Virgin Islands (U.S.)", R.drawable.vi),
        Country("Viet Nam", R.drawable.vn),
        Country("Vanuatu", R.drawable.vu),
        Country("Wallis and Futuna", R.drawable.wf),
        Country("Samoa", R.drawable.ws),
        Country("Yemen", R.drawable.ye),
        Country("Mayotte", R.drawable.yt),
        Country("South Africa", R.drawable.za),
        Country("Zambia", R.drawable.zm),
        Country("Zimbabwe", R.drawable.zw)
    ).sortedBy { it.name }
}
